project:
  useAWS: False 
  awsSetup:
    bucket: projects.irll # working bucket in AWS
    region: ca-central-1 # working AWS region
    rootDomain: irll.net # a fully qualified domain name without 'https://'
    cpu: 2 # int 1,2, or 4
    memory: 10 # int 1-30

  events:
    startServerStep: 1 # int ? #this
    stopServerStep: 9  # int ?
  id: humanfeedback-s # Letters, Numbers and '-' only! #only lower case #change this
  live: True # bool
  maxRuntime: 20 # int in minutes.
  name: human_feedback_no_strat # str #change this 
  researcher: Callie Muslimani
  ssl:
    fullchain: SSL/fullchain.pem # path to fullchain.pem file excluding bucket name
    privkey: SSL/privkey.pem # path to privkey.pem file excluding bucket name
    sslBucket: projects.irll # bucket name for resolving paths above

  steps: #in the step file folder # any number of steps needed with corresponding filenames
    1: consentForm.html
    2: initialsurvey.html
    3: humanstrategy.html
    4: lavaworldinstructions.html
    5: game
    6: next_trial.html
    7: game
    8: postgamesurvey.html
    9: exampleThank.html
    #finalStep:  #put the file name of the last step again here # required, filename can be same as last numbered step
  teamMembers: Callie # str
trial:
  actionBufferLifespan: 0 # int ? #maybe 1 and 3
  maxEpisodes: 20 # int 
  game: Lava_World # full environment name
  dataFile: episode # episode or trial
  s3upload: False #maybe turn this into False
  actionSpace: # the appropriate action space for environment. Order matters
    #- noop
    #- up
    #- right
    #- left
    #- down
    #- upright
    #- upleft
    #- downright
    #- downleft
    #- AccelerateLeft #0
    #- noaccelerate #1
    #- AccelerateRight #2

    #- left
    #- do_nothing
    #- right
    - up
    - down
    - left
    - right 

    - #pickup
    - #drop
    - #toggle

  frameRateStepSize: 1 # int Optional if allowFrameRateChange = False
  minFrameRate: 1 # int Optional if allowFrameRateChange = False
  maxFrameRate: 1 # int Optional if allowFrameRateChange = False
  allowFrameRateChange: False # bool
  startingFrameRate: 1  # int Required #may need to change  #10 for cartpole
  columns: 9
  rows: 6
  blockedStates: # self.blocked_states= [(1,2), (2,2),(3,2),(4,5), (0,7),(1,7), (2,7)]
    - { x: 1, y: 2 }
    - { x: 2, y: 2 }
    - { x: 3, y: 2 }
    - { x: 4, y: 5 }
    - { x: 0, y: 7 }
    - { x: 1, y: 7 }
    - { x: 2, y: 7 }
  ui: # to include ui button set to True, False buttons will not be shown
    left: False
    right: False
    up: False
    down: False
    start: True
    stop: True
    pause: True
    reset: True
    trainOffline: False
    trainOnline: False
    good: True
    bad: True
    reallygood: False
    fpsSet: False
    fpsUp: False
    fpsDown: False
    next: False
